modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/DinnerBeef/Compressium"

[[mods]]
modId="compressium"
version="${file.jarVersion}"
displayName="Compressium"
displayURL="http://dinnerbeef.com"
logoFile=""
credits="Thanks to LatvianModder for helping me clean up this code. Thanks To Gigaherz For the textures"
authors="DinnerBeef"
description=''' Adding comprseed blocks to the game since 2019 '''
